# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[git_status]
format = '([$ahead_behind$conflicted$stashed$deleted$renamed$modified$staged$untracked]($style))'
ahead = '⇡$count '
behind = '⇣$count '
diverged = '⇡$ahead_count ⇣$behind_count '
untracked = '?$count '
stashed = '\$$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = 'x$count '

[cmake]
disabled = true

[python]
disabled = true

[rust]
disabled = true
