vim.opt.fileencoding = "utf-8"                  -- the encoding written to a file
vim.opt.shiftwidth = 2                          -- the number of spaces inserted for each indentation
vim.opt.tabstop = 2                             -- insert 2 spaces for a tab
vim.opt.expandtab = true                        -- convert tabs to spaces
vim.opt.smartindent = true                      -- make indenting smarter again
vim.opt.number = true                           -- set numbered lines
vim.opt.relativenumber = true                   -- set relative line numbers
vim.opt.mouse = "a"                             -- allow the mouse to be used in neovim
vim.opt.ignorecase = true                       -- ignore case in search patterns
vim.opt.smartcase = true                        -- ignore "ignore case" if search term has uppercase characters
vim.opt.termguicolors = true                    -- set term gui colors (most terminals support this)
vim.opt.undofile = true                         -- enable persistent undo
vim.opt.updatetime = 300                        -- faster completion (4000ms default)
vim.opt.scrolloff = 8                           -- always keep this many lines above/below cursor
vim.opt.sidescrolloff = 8												-- always keep this many lines before/after cursor
vim.opt.signcolumn = "yes"                      -- keep sign column (left of number column) always enabled - this avoids layout shift when diagnostic signs appear
vim.opt.cursorline = true                       -- highlight cursor line
vim.opt.showmode = false                        -- covered by lualine plugin
