theme = "monokai_pro"

[editor]
true-color = true
line-number = "relative"
idle-timeout = 100
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
git-global = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "primary-selection-length", "position", "position-percentage", "file-encoding"]

[keys.normal]
"space" = { t = ":format" }

[keys.insert]
j = { k = "normal_mode" }
